# Generated by Django 4.0 on 2022-02-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('femaile', 'Female'), ('others', 'Others')], default='male', max_length=20)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('works_at', models.CharField(blank=True, max_length=200, null=True)),
                ('lives_in', models.CharField(blank=True, max_length=200, null=True)),
                ('studies_at', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='auth.user')),
            ],
        ),
    ]
