# Generated by Django 4.0 on 2022-02-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('categories', models.CharField(blank=True, default=None, max_length=3000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='auth.user')),
            ],
        ),
    ]
